/* This file was generated by PyMbs on 2022-01-13 19:26:02 UTC */
using System;
using MathNet.Numerics.LinearAlgebra;

int pendulum_visual(Vector<double> y, out Vector<double> r_visual_1, out Matrix<double> T_visual_1)
{
    /* declare state variables */
    double q = y[0]; /*q*/

    /* Parameters */
    double l = 1;  /*l*/

    /* Constants */

    /* User Expression variables */

    /* ordinary variables */
    double cosq_joint_1_Ry = 0; 
    double sinq_joint_1_Ry = 0; 

    /* calculate visual sensors */
    cosq_joint_1_Ry = Math.Cos(q);
    T_visual_1[2,2] = cosq_joint_1_Ry;
    r_visual_1[2] = (-(0.5 * l * T_visual_1[2,2]));
    sinq_joint_1_Ry = Math.Sin(q);
    T_visual_1[0,2] = sinq_joint_1_Ry;
    r_visual_1[0] = (-(0.5 * l * T_visual_1[0,2]));
    T_visual_1[1,2] = 0;
    r_visual_1[1] = (-(0.5 * l * T_visual_1[1,2]));
    T_visual_1[0,1] = 0;
    T_visual_1[1,1] = 1;
    T_visual_1[0,0] = cosq_joint_1_Ry;
    T_visual_1[1,0] = 0;
    T_visual_1[2,0] = (-sinq_joint_1_Ry);
    T_visual_1[2,1] = 0;


	return 0;
}
